# Generated by Django 3.1.7 on 2021-03-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210310_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav_player',
            name='position',
            field=models.CharField(default='P', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fav_player',
            name='team',
            field=models.CharField(default='NYY', max_length=10),
            preserve_default=False,
        ),
    ]
