# Generated by Django 3.1.7 on 2021-03-10 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210310_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fav_player',
            old_name='position',
            new_name='pos',
        ),
    ]
