# Generated by Django 3.1.7 on 2021-03-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210310_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav_player',
            name='name',
            field=models.CharField(default='Test Name', max_length=100),
            preserve_default=False,
        ),
    ]
